core:
  port: 9090
  enable: true
  workers: 1
  secret: "secret"
mysql:
  host: 'localhost'
  port: 3306
  user: root
  pass: 'Amir2222'
  database: 'apt'
  migrate: false
migrate:
  root: 'admin'
  pass: '12345'
  enable: false
ftp:
  host: 'http://localhost:9091'
  secret: 'secret'
  access: 'access'
